<?php
namespace Heroes\enums;

abstract class Skills {
    const CLIMBING = 'Climbing';
    const CONCEALMENT = 'Concealment';
    const ELECTRICAL_REPAIR = 'Electrical Repair';
    const ESCAPE_ARTIST = 'Escape Artist';
    const LANGUAGE = 'Language';
    const MECHANICAL_REPAIR = 'Mechanical Repair';
    const PALMING = 'Palming';
    const PICK_LOCKS = 'Pick Locks';
    const PICK_POCKET = 'Pick Pocket';
    const PROWL = 'Prowl';
    const SWIMMING = 'Swimming';
}
